# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from multi_bspline_opt/SendTraj.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import geometry_msgs.msg

class SendTraj(genpy.Message):
  _md5sum = "cdb4d98dc8568f5ace0ee75482493f76"
  _type = "multi_bspline_opt/SendTraj"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 drone_id
int64 traj_id
int32 order
int32 cps_num_
# int32 Dim_
# int32 TrajSampleRate
# float64 beta
time start_time


float64 start_pos_x
float64 start_pos_y
float64 start_vel_x
float64 start_vel_y
float64 end_pos_x
float64 end_pos_y
# float64 yaw_rate

geometry_msgs/Point[] control_pts
float64[] knots
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['drone_id','traj_id','order','cps_num_','start_time','start_pos_x','start_pos_y','start_vel_x','start_vel_y','end_pos_x','end_pos_y','control_pts','knots']
  _slot_types = ['int32','int64','int32','int32','time','float64','float64','float64','float64','float64','float64','geometry_msgs/Point[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       drone_id,traj_id,order,cps_num_,start_time,start_pos_x,start_pos_y,start_vel_x,start_vel_y,end_pos_x,end_pos_y,control_pts,knots

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SendTraj, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.drone_id is None:
        self.drone_id = 0
      if self.traj_id is None:
        self.traj_id = 0
      if self.order is None:
        self.order = 0
      if self.cps_num_ is None:
        self.cps_num_ = 0
      if self.start_time is None:
        self.start_time = genpy.Time()
      if self.start_pos_x is None:
        self.start_pos_x = 0.
      if self.start_pos_y is None:
        self.start_pos_y = 0.
      if self.start_vel_x is None:
        self.start_vel_x = 0.
      if self.start_vel_y is None:
        self.start_vel_y = 0.
      if self.end_pos_x is None:
        self.end_pos_x = 0.
      if self.end_pos_y is None:
        self.end_pos_y = 0.
      if self.control_pts is None:
        self.control_pts = []
      if self.knots is None:
        self.knots = []
    else:
      self.drone_id = 0
      self.traj_id = 0
      self.order = 0
      self.cps_num_ = 0
      self.start_time = genpy.Time()
      self.start_pos_x = 0.
      self.start_pos_y = 0.
      self.start_vel_x = 0.
      self.start_vel_y = 0.
      self.end_pos_x = 0.
      self.end_pos_y = 0.
      self.control_pts = []
      self.knots = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_iq2i2I6d().pack(_x.drone_id, _x.traj_id, _x.order, _x.cps_num_, _x.start_time.secs, _x.start_time.nsecs, _x.start_pos_x, _x.start_pos_y, _x.start_vel_x, _x.start_vel_y, _x.end_pos_x, _x.end_pos_y))
      length = len(self.control_pts)
      buff.write(_struct_I.pack(length))
      for val1 in self.control_pts:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.knots)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.knots))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      if self.control_pts is None:
        self.control_pts = None
      end = 0
      _x = self
      start = end
      end += 76
      (_x.drone_id, _x.traj_id, _x.order, _x.cps_num_, _x.start_time.secs, _x.start_time.nsecs, _x.start_pos_x, _x.start_pos_y, _x.start_vel_x, _x.start_vel_y, _x.end_pos_x, _x.end_pos_y,) = _get_struct_iq2i2I6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.control_pts = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.control_pts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.knots = s.unpack(str[start:end])
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_iq2i2I6d().pack(_x.drone_id, _x.traj_id, _x.order, _x.cps_num_, _x.start_time.secs, _x.start_time.nsecs, _x.start_pos_x, _x.start_pos_y, _x.start_vel_x, _x.start_vel_y, _x.end_pos_x, _x.end_pos_y))
      length = len(self.control_pts)
      buff.write(_struct_I.pack(length))
      for val1 in self.control_pts:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.knots)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.knots.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.start_time is None:
        self.start_time = genpy.Time()
      if self.control_pts is None:
        self.control_pts = None
      end = 0
      _x = self
      start = end
      end += 76
      (_x.drone_id, _x.traj_id, _x.order, _x.cps_num_, _x.start_time.secs, _x.start_time.nsecs, _x.start_pos_x, _x.start_pos_y, _x.start_vel_x, _x.start_vel_y, _x.end_pos_x, _x.end_pos_y,) = _get_struct_iq2i2I6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.control_pts = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.control_pts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.knots = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      self.start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_iq2i2I6d = None
def _get_struct_iq2i2I6d():
    global _struct_iq2i2I6d
    if _struct_iq2i2I6d is None:
        _struct_iq2i2I6d = struct.Struct("<iq2i2I6d")
    return _struct_iq2i2I6d
